import { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "aggie-pantry",
    title: "The Aggie Pantry",
    summary: "A web app built at HackDavis 2025 to streamline food access for UC Davis students.",
    problem: "Manual checkout caused queues and data loss in food pantry operations.",
    solution: "Features real-time inventory browsing, AI-powered recipe suggestions, QR code checkout, and admin dashboard with secure authentication.",
    impact: "Won 'Best Use of Auth0' for secure authentication with MFA; faster checkout; improved tracking. View our pitch deck and Devpost submission for more details.",
    role: "Full-stack developer + product design.",
    stack: ["React", "Django", "TypeScript", "TensorFlow.js", "TailwindCSS", "Auth0", "Cisco Duo", "PostgreSQL"],
    tags: ["Full-Stack", "AI", "Civic"],
    heroImage: "/AggiePantry.png",
    featured: true,
    year: "2025",
    repo: "https://github.com/Adamy8/theaggiepantry",
    live: "https://theaggiepantry.vercel.app/",
    presentation: "https://pitch.com/v/aggie-pantry-knpg2m",
    devpost: "https://devpost.com/software/the-aggie-pantry",
  },
  {
    slug: "wildalert-models-api",
    title: "WildAlert Models API",
    summary: "An API-powered Gradio app for anomaly detection in wildlife disease surveillance data.",
    problem: "Wildlife disease surveillance data needs automated anomaly detection for early warning systems.",
    solution: "Implements Isolation Forest, Autoencoder, and Statistical Threshold models with JSON input/output for real-time analysis.",
    impact: "Deployed on Hugging Face Spaces to support real-time exploration and validation of model results.",
    role: "ML Engineer + API Developer.",
    stack: ["Python", "Gradio", "Scikit-learn", "TensorFlow", "JSON", "Pandas", "Hugging Face Spaces"],
    tags: ["AI", "ML", "API", "Data Science"],
    heroImage: "/WildAlert.png",
    featured: true,
    year: "2025",
    repo: "https://huggingface.co/spaces/smartha2003/WildAlertModelAPI/tree/main",
    live: "https://huggingface.co/spaces/smartha2003/WildAlertModelAPI",
  },
  {
    slug: "gdsc-website",
    title: "GDSC Website",
    summary: "GDSC website built with React and TypeScript for events, resources, and community updates.",
    problem: "Student club needed a centralized platform for events, resources, and community engagement.",
    solution: "Modern React website with event management, resource library, and community features.",
    impact: "Improved student engagement and streamlined club operations.",
    role: "Frontend developer + UI/UX design.",
    stack: ["React", "TypeScript", "TailwindCSS", "Vercel", "SQL"],
    tags: ["Frontend", "Community", "Education"],
    heroImage: "/GDSC.png",
    featured: true,
    year: "2025",
    repo: "https://github.com/shubhadamartha/gdsc-website",
    live: "https://gdsc-ucdavis.vercel.app",
  },
  {
    slug: "toolcraft-agent",
    title: "ToolCraft Agent",
    summary: "An agentic AI system with deployment capabilities for intelligent tool usage and automation.",
    problem: "Complex workflows require intelligent agents that can use tools and deploy solutions autonomously.",
    solution: "Agentic AI system that can understand tasks, select appropriate tools, and deploy solutions with minimal human intervention.",
    impact: "Demonstrates advanced AI agent capabilities with real-world deployment on Hugging Face Spaces.",
    role: "AI Engineer + Deployment Specialist.",
    stack: ["Python", "LangChain", "Hugging Face", "AI Agents", "Deployment"],
    tags: ["AI", "LLM Applications", "Agentic AI", "Deployment"],
    heroImage: "/WildAlert.png",
    featured: false,
    year: "2025",
    repo: "https://github.com/smartha2003/toolcraft",
    live: "https://huggingface.co/spaces/smartha2003/toolcraft-agent",
  },
  {
    slug: "dsld-r-package",
    title: "DSLD R Package",
    summary: "Statistical and graphical tools designed to detect and measure discrimination and bias.",
    problem: "Need for comprehensive tools to detect and measure various forms of discrimination in data.",
    solution: "R package with functions for detecting racial, gender, age, and other forms of bias in statistical models.",
    impact: "Enabled researchers to identify and quantify discrimination in various datasets.",
    role: "Statistical software developer + researcher.",
    stack: ["R", "Python", "Statistics", "Machine Learning"],
    tags: ["Research", "Statistics", "Social Impact"],
    heroImage: "/DSLD.png",
    featured: true,
    year: "2024",
    repo: "https://github.com/matloff/dsld",
    paper: "https://arxiv.org/abs/2411.04228",
    quarto: "https://htmlpreview.github.io/?https://github.com/matloff/dsldBook/blob/main/_book/index.html",
  },
  {
    slug: "calshare",
    title: "CalShare",
    summary: "CalShare simplifies calendar sharing and scheduling by syncing Apple and Google Calendars.",
    problem: "Cross-platform calendar synchronization and shared scheduling is complex and fragmented.",
    solution: "iOS app that syncs Apple and Google Calendars, displaying shared free time slots for easy scheduling.",
    impact: "Simplified cross-platform calendar management and group scheduling.",
    role: "iOS developer + API integration.",
    stack: ["Swift", "Firebase", "Google Auth", "Google & iOS Calendar API"],
    tags: ["Mobile", "Productivity", "iOS", "Full-Stack"],
    heroImage: "/CalShare.png",
    featured: true,
    year: "2024",
    repo: "https://github.com/smartha2003/CalShare",
  },
  {
    slug: "payvault",
    title: "PayVault",
    summary: "PayVault is an iOS mobile wallet app that securely stores your debit and credit cards.",
    problem: "Need for secure, user-friendly mobile wallet solution for card management.",
    solution: "Mobile wallet with secure card storage, phone verification, and financial protection features.",
    impact: "Provided secure financial management solution with OTP verification.",
    role: "iOS developer + security implementation.",
    stack: ["Swift", "PhoneNumberKit", "API implementation", "Phone Verification via OTP"],
    tags: ["Mobile", "FinTech", "Security", "iOS"],
    heroImage: "/PayVault.png",
    featured: true,
    year: "2024",
    repo: "https://github.com/smartha2003/PayVault",
  },
  /*
  {
    slug: "dailymood",
    title: "DailyMOOD",
    summary: "A product focused on UX design and writing for mood tracking and mental wellness.",
    problem: "Users need intuitive ways to track and understand their emotional patterns over time.",
    solution: "Product design focused on user experience with thoughtful writing and UX principles for mood tracking.",
    impact: "Demonstrated product thinking, UX design, and writing skills in mental health technology.",
    role: "Product Designer + UX Writer.",
    stack: ["Product Design", "UX/UI", "Writing", "User Research"],
    tags: ["Product", "UX", "Writing", "HealthTech"],
    heroImage: "/CalShare.png",
    featured: false,
    year: "2024",
    article: "https://codelabdavis.medium.com/daily-mood-5aa946535a53",
  },
  {
    slug: "kultrify",
    title: "Kultrify",
    summary: "User research and design thinking project focused on cultural connection and community building.",
    problem: "Need for platforms that facilitate cultural connection and community engagement.",
    solution: "Design thinking approach with comprehensive user research, prototyping, and iterative design.",
    impact: "Showcased user research methodologies and design thinking processes.",
    role: "User Researcher + Design Thinker.",
    stack: ["User Research", "Design Thinking", "Figma", "Canva", "Prototyping"],
    tags: ["Design", "User Research", "Design Thinking"],
    heroImage: "/CalShare.png",
    featured: false,
    year: "2024",
    canva: "https://www.canva.com/design/DAG_xf73rdY/kqrEaFfcSin4dIO-StYM4A/edit?utm_content=DAG_xf73rdY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton",
    figma: "https://www.figma.com/proto/CRaq2F4ouqnl10SA9TheWn/cmn_app_design?node-id=21-2387&starting-point-node-id=21%3A2387",
  },
  {
    slug: "mitigating-bias-ml",
    title: "Mitigating Bias in ML",
    summary: "Theoretical foundations and research on mitigating bias in machine learning systems.",
    problem: "Machine learning systems can perpetuate and amplify societal biases, requiring theoretical understanding and mitigation strategies.",
    solution: "Research and theoretical work on bias detection, measurement, and mitigation techniques in ML systems.",
    impact: "Contributed to understanding of bias in ML systems and theoretical foundations for fairness.",
    role: "Researcher + ML Theorist.",
    stack: ["Machine Learning", "Statistics", "Theory", "Research"],
    tags: ["Research", "Machine Learning", "Theory", "Social Impact"],
    heroImage: "/DSLD.png",
    featured: false,
    year: "2024",
    paper: "pdf",
  },
  {
    slug: "crypgo",
    title: "CrypGo",
    summary: "A project focused on cryptography and secure communication systems.",
    problem: "Need for secure and efficient cryptographic solutions for modern applications.",
    solution: "Implementation of cryptographic algorithms and secure communication protocols.",
    impact: "Demonstrated understanding of cryptography principles and secure system design.",
    role: "Developer + Security Engineer.",
    stack: ["Cryptography", "Security", "Go", "Algorithms"],
    tags: ["Security", "Cryptography", "Backend Development"],
    heroImage: "/CalShare.png",
    featured: false,
    year: "2024",
    repo: "https://github.com/smartha2003/CrypGo",
    canva: "https://www.canva.com/design/DAG_xYv-ZTA/tM8tijIUmQqmvF4w4SYDxw/edit?utm_content=DAG_xYv-ZTA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton",
  },
  */
];
