import { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "aggie-pantry",
    title: "The Aggie Pantry",
    summary: "A web app built at HackDavis 2025 to streamline food access for UC Davis students.",
    problem: "Manual checkout caused queues and data loss in food pantry operations.",
    solution: "Features real-time inventory browsing, AI-powered recipe suggestions, QR code checkout, and admin dashboard with secure authentication.",
    impact: "Won 'Best Use of Auth0' for secure authentication with MFA; faster checkout; improved tracking. View our pitch deck and Devpost submission for more details.",
    role: "Full-stack developer + product design.",
    stack: ["React", "Django", "TypeScript", "TensorFlow.js", "TailwindCSS", "Auth0", "Cisco Duo", "PostgreSQL"],
    tags: ["Full-Stack", "AI", "Civic"],
    heroImage: "/portfolio/AggiePantry.png",
    featured: true,
    year: "2025",
    repo: "https://pitch.com/v/aggie-pantry-knpg2m",
    live: "https://theaggiepantry.vercel.app/",
  },
  {
    slug: "wildalert-models-api",
    title: "WildAlert Models API",
    summary: "An API-powered Gradio app for anomaly detection in wildlife disease surveillance data.",
    problem: "Wildlife disease surveillance data needs automated anomaly detection for early warning systems.",
    solution: "Implements Isolation Forest, Autoencoder, and Statistical Threshold models with JSON input/output for real-time analysis.",
    impact: "Deployed on Hugging Face Spaces to support real-time exploration and validation of model results.",
    role: "ML Engineer + API Developer.",
    stack: ["Python", "Gradio", "Scikit-learn", "TensorFlow", "JSON", "Pandas", "Hugging Face Spaces"],
    tags: ["AI", "ML", "API", "Data Science"],
    heroImage: "/portfolio/WildAlert.png",
    featured: true,
    year: "2024",
    repo: "https://github.com/shubhadamartha/wildalert-models-api",
    live: "https://huggingface.co/spaces/shubhadamartha/wildalert-models",
  },
  {
    slug: "gdsc-website",
    title: "GDSC Website",
    summary: "Google Developer Student Club's official website for events, resources, and community updates.",
    problem: "Student club needed a centralized platform for events, resources, and community engagement.",
    solution: "Modern React website with event management, resource library, and community features.",
    impact: "Improved student engagement and streamlined club operations.",
    role: "Frontend developer + UI/UX design.",
    stack: ["React", "TypeScript", "TailwindCSS", "Vercel", "SQL"],
    tags: ["Frontend", "Community", "Education"],
    heroImage: "/portfolio/GDSC.png",
    featured: true,
    year: "2024",
    repo: "https://github.com/shubhadamartha/gdsc-website",
    live: "https://gdsc-ucdavis.vercel.app",
  },
  {
    slug: "truckpedia",
    title: "TruckPedia",
    summary: "A mobile app for Truckpedia that streamlines communication for shippers, brokers, and carriers.",
    problem: "Complex logistics coordination between shippers, brokers, and carriers needed better communication tools.",
    solution: "Mobile app with load assignment, real-time updates, and revenue tracking for all stakeholders.",
    impact: "Streamlined logistics operations and improved communication efficiency.",
    role: "Mobile developer + backend integration.",
    stack: ["React Native", "TypeScript", "Node.js", "Express"],
    tags: ["Mobile", "Logistics", "Full-Stack"],
    heroImage: "/portfolio/PayVault.png",
    featured: false,
    year: "2024",
    repo: "https://github.com/shubhadamartha/truckpedia",
  },
  {
    slug: "dsld-r-package",
    title: "DSLD R Package",
    summary: "Statistical and graphical tools designed to detect and measure discrimination and bias.",
    problem: "Need for comprehensive tools to detect and measure various forms of discrimination in data.",
    solution: "R package with functions for detecting racial, gender, age, and other forms of bias in statistical models.",
    impact: "Enabled researchers to identify and quantify discrimination in various datasets.",
    role: "Statistical software developer + researcher.",
    stack: ["R", "Python", "Statistics", "Machine Learning"],
    tags: ["Research", "Statistics", "Social Impact"],
    heroImage: "/portfolio/DSLD.png",
    featured: true,
    year: "2024",
    repo: "https://github.com/shubhadamartha/dsld-r-package",
  },
  {
    slug: "calshare",
    title: "CalShare",
    summary: "CalShare simplifies calendar sharing and scheduling by syncing Apple and Google Calendars.",
    problem: "Cross-platform calendar synchronization and shared scheduling is complex and fragmented.",
    solution: "iOS app that syncs Apple and Google Calendars, displaying shared free time slots for easy scheduling.",
    impact: "Simplified cross-platform calendar management and group scheduling.",
    role: "iOS developer + API integration.",
    stack: ["Swift", "Firebase", "Google Auth", "Google & iOS Calendar API"],
    tags: ["Mobile", "Productivity", "iOS"],
    heroImage: "/portfolio/CalShare.png",
    featured: true,
    year: "2024",
    repo: "https://github.com/shubhadamartha/calshare",
  },
  {
    slug: "froggyvault",
    title: "PayVault / FroggyVault",
    summary: "PayVault is a mobile wallet app that securely stores your debit and credit cards.",
    problem: "Need for secure, user-friendly mobile wallet solution for card management.",
    solution: "Mobile wallet with secure card storage, phone verification, and financial protection features.",
    impact: "Provided secure financial management solution with OTP verification.",
    role: "iOS developer + security implementation.",
    stack: ["Swift", "PhoneNumberKit", "API implementation", "Phone Verification via OTP"],
    tags: ["Mobile", "FinTech", "Security"],
    heroImage: "/portfolio/PayVault.png",
    featured: true,
    year: "2024",
    repo: "https://github.com/shubhadamartha/froggyvault",
  },
  {
    slug: "gradio-anomaly-detector",
    title: "Gradio Anomaly Detector",
    summary: "Interactive ML tool for time series anomaly detection with real-time visualization.",
    problem: "Complex anomaly detection models need accessible interfaces for non-technical users.",
    solution: "Gradio interface with isolation forest and autoencoder models; real-time data visualization and threshold tuning.",
    impact: "Enabled non-technical users to detect anomalies in time series data; reduced setup time from hours to minutes.",
    role: "ML Engineer + Frontend Developer.",
    stack: ["Python", "Gradio", "Scikit-learn", "Pandas", "NumPy", "Matplotlib"],
    tags: ["AI", "ML", "Python", "Data Science"],
    heroImage: "/portfolio/WildAlert.png",
    featured: false,
    year: "2024",
    repo: "https://github.com/shubhadamartha/gradio-anomaly-detector",
  },
  {
    slug: "recipe-bot",
    title: "Recipe Bot — AI Cooking Assistant",
    summary: "LangChain-powered cooking assistant with ingredient substitution and dietary restriction handling.",
    problem: "Cooking apps don't adapt to dietary restrictions or missing ingredients intelligently.",
    solution: "LangChain orchestration for recipe modification; ingredient substitution logic; dietary restriction filtering.",
    impact: "Improved recipe accessibility for users with dietary restrictions; reduced food waste through better substitutions.",
    role: "Full-stack developer + AI integration.",
    stack: ["Python", "LangChain", "FastAPI", "React", "PostgreSQL"],
    tags: ["AI", "Full-stack", "LangChain", "Food Tech"],
    heroImage: "/portfolio/CalShare.png",
    featured: false,
    year: "2024",
    repo: "https://github.com/shubhadamartha/recipe-bot",
  },
];
